version: "3.8"

services:
  api:
    build: ../bolvanka_fastapi
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    depends_on:
      - mongodb

  bot:
    build:
      context: "../bolvanka_bot"
      dockerfile: Dockerfile
    env_file: ../bolvanka_bot/.env
    volumes:
      - .:/src
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    volumes:
      - mongo_data:/var/lib/mongodb/data/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    ports:
      - "27014:27014"

volumes:
  mongo_data:
